name: Build .NET Framework Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore StoneshardSaveEditor.sln

    - name: Build the solution
      run: msbuild StoneshardSaveEditor.sln /p:Configuration=Release /p:Platform="Any CPU" /verbosity:minimal

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: StoneshardSaveEditor
        path: |
          **\bin\Release\*.exe
          **\bin\Release\*.dll
          **\bin\Release\*.config
